# Generated by Django 5.2.6 on 2025-09-13 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_order_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Customer',
            new_name='customer',
        ),
    ]
