# Generated by Django 5.2.6 on 2025-09-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.ManyToManyField(related_name='product', to='app.category'),
        ),
    ]
